const EXTENDED_PHASES = [
  { id: 1, name: "Deep Metabolism Reset", range: "Month 2", icon: "🔥", color: "from-orange-500 to-amber-600", months: "Days 31–60", desc: "Rewire your metabolic furnace to burn fat on autopilot." },
  { id: 2, name: "Hormonal Harmony", range: "Month 3", icon: "🌸", color: "from-pink-500 to-rose-600", months: "Days 61–90", desc: "Rebalance estrogen, cortisol, and thyroid for effortless weight management." },
  { id: 3, name: "Body Recomposition", range: "Month 4", icon: "💪", color: "from-emerald-500 to-green-600", months: "Days 91–120", desc: "Replace stubborn fat with lean, toned muscle definition." },
  { id: 4, name: "Anti-Aging & Vitality", range: "Month 5", icon: "✨", color: "from-violet-500 to-purple-600", months: "Days 121–150", desc: "Activate your youth genes — skin, hair, nails, and cellular energy." },
  { id: 5, name: "Lifestyle Integration", range: "Month 6", icon: "🧘", color: "from-teal-500 to-cyan-600", months: "Days 151–180", desc: "Lock in your results forever. No more yo-yo. This becomes who you are." },
  { id: 6, name: "Mastery & Maintenance", range: "Month 7", icon: "👑", color: "from-amber-500 to-yellow-600", months: "Days 181–210", desc: "Fine-tune, optimize, and teach your body to self-regulate." },
];

const MORNING_SHOTS = [
  "1/2 tsp baking soda + juice of 1/2 lemon + pinch of cayenne in 8oz warm water.",
  "1 tbsp apple cider vinegar + 1/4 tsp cinnamon + 8oz warm water.",
  "Ginger-turmeric shot: 1/4 tsp each of ginger and turmeric powder + black pepper in 4oz warm water.",
  "Green tea with 1/2 tsp matcha whisked in + squeeze of lemon.",
  "1 tbsp chia seeds soaked 10 min in 8oz lemon water.",
  "Peppermint + ginger tea blend — steep 5 minutes, sip slowly.",
  "1/4 tsp ashwagandha + 1/4 tsp maca in warm almond milk.",
  "Dandelion root tea with a pinch of cinnamon.",
  "1 tbsp apple cider vinegar + 1/4 tsp turmeric + 8oz water.",
  "Bone broth (1 cup) with fresh ginger slice and sea salt.",
  "Oolong tea steeped 4 minutes + dash of raw honey.",
  "1/2 tsp baking soda + 1 tbsp lemon juice + 1/4 tsp grated fresh ginger.",
  "Rooibos tea with a pinch of cinnamon and cardamom.",
  "1 tsp coconut oil melted into black coffee — blend until frothy.",
  "Chamomile-lavender tea with 1/4 tsp ashwagandha.",
  "Fresh ginger tea (3 slices steeped 10 min) + 1/2 tsp honey.",
  "Moringa tea: 1/2 tsp moringa powder in hot water + lemon.",
  "1 tbsp flaxseed meal stirred into warm lemon water.",
  "Hibiscus tea steeped 7 minutes — naturally lowers blood pressure and bloating.",
  "1/4 tsp cinnamon + 1/4 tsp ginger in warm water with 1 tsp honey.",
  "Fennel seed tea: 1 tsp crushed fennel seeds steeped 8 min.",
  "1/2 tsp spirulina blended into 8oz coconut water.",
  "Nettle leaf tea — steep 10 min for a mineral-rich morning boost.",
  "Warm water + 1 tbsp lemon juice + pinch of Himalayan salt.",
  "Cacao + maca latte: 1 tsp raw cacao + 1/2 tsp maca in warm oat milk.",
  "Rosemary-lemon infusion: 1 sprig rosemary + lemon slices in hot water.",
  "1/4 tsp turmeric + 1/4 tsp black pepper + coconut milk — golden milk shot.",
  "Licorice root tea steeped 5 min — supports adrenal function.",
  "1 tbsp apple cider vinegar + fresh mint leaves in 8oz cool water.",
  "Matcha latte: 1 tsp matcha + warm oat milk + 1/4 tsp vanilla.",
];

const DAILY_TIPS = [
  "Walk for 10 minutes after your largest meal. Post-meal walking reduces blood sugar spikes by 30% and prevents fat storage.",
  "Eat your protein first at every meal. It triggers satiety hormones faster and keeps you full longer.",
  "Add a pinch of cinnamon to anything sweet. It blunts insulin response and reduces cravings for hours.",
  "Stand up and stretch for 2 minutes every hour. Sedentary time shuts down lipase, the enzyme that burns fat.",
  "Chew each bite 20 times. Digestion starts in your mouth — this alone can reduce bloating by 40%.",
  "End your shower with 30 seconds of cold water. It activates brown fat, which burns calories to generate heat.",
  "Stop eating 3 hours before bed. Late-night eating disrupts growth hormone, which drives overnight fat burning.",
  "Swap one starchy side for leafy greens today. The fiber feeds your good bacteria and keeps blood sugar stable.",
  "Take 5 deep belly breaths before eating. This shifts your nervous system into 'rest and digest' mode.",
  "Drink a full glass of water 20 minutes before each meal. Studies show this reduces calorie intake by 75 calories per meal.",
  "Eat a handful of nuts (almonds or walnuts) as your afternoon snack. The healthy fats keep cortisol from spiking.",
  "Get 15 minutes of morning sunlight. It resets your circadian clock and optimizes metabolic hormones.",
  "Add fermented food to one meal today — yogurt, sauerkraut, or kimchi. Your gut bacteria will thank you.",
  "Replace one sugary drink with sparkling water + lemon. Liquid sugar is the fastest path to belly fat.",
  "Do 10 squats right now. Micro-exercise bursts boost GLUT-4 receptors, improving how your cells use sugar.",
  "Cook with olive oil instead of vegetable oil. Olive oil reduces inflammation; seed oils increase it.",
  "Eat slowly and put your fork down between bites. It takes 20 minutes for your brain to register fullness.",
  "Have your last coffee before 2 PM. Afternoon caffeine disrupts deep sleep, where most fat burning happens.",
  "Add garlic to your cooking today. Allicin in garlic boosts thermogenesis and supports immune function.",
  "Practice the '80% full' rule. Stop eating when you're satisfied, not stuffed. Your body catches up in 20 minutes.",
  "Dry brush your skin before your shower — upward strokes toward the heart. It boosts lymph flow and reduces cellulite.",
  "Eat the rainbow today: aim for 5 different colored vegetables. Each color provides different phytonutrients.",
  "Take a 20-minute evening walk. It lowers cortisol, improves sleep quality, and gently burns fat.",
  "Try replacing table salt with Himalayan pink salt. The trace minerals support thyroid function.",
  "Massage your belly in clockwise circles for 2 minutes. This follows the colon path and improves digestion.",
  "Avoid eating fruit after 4 PM. The fructose is more likely to be stored as fat when insulin sensitivity drops.",
  "Do 10 minutes of stretching before bed. It lowers cortisol and primes your body for deep restorative sleep.",
  "Have bone broth as an afternoon snack. The collagen and amino acids repair your gut and tighten skin.",
  "Laugh more today — seriously. Laughing for 10 minutes burns up to 40 calories and reduces stress hormones.",
  "Smell peppermint when you feel a craving. Studies show peppermint aroma reduces appetite by up to 23%.",
  "Set a timer and drink water every hour. Most hunger between meals is actually thirst in disguise.",
  "Eat on smaller plates. The visual trick reduces portions by 20-30% without feeling deprived.",
  "Try 'earthing' — walk barefoot on grass for 5 minutes. It reduces inflammation markers measurably.",
  "Replace one snack with green tea. EGCG increases fat oxidation by 17% over 24 hours.",
  "Write down 3 things you're grateful for. Gratitude practice lowers cortisol, which directly reduces belly fat.",
  "Stand on one leg while brushing your teeth. Balance exercises activate deep core muscles and improve posture.",
  "Eat avocado today. The monounsaturated fats specifically target visceral belly fat for removal.",
  "Hum while exhaling — it stimulates the vagus nerve and shifts your body into fat-burning parasympathetic mode.",
  "Wear something that makes you feel confident today. Self-image directly affects cortisol levels.",
  "Prep tomorrow's meals today. Decision fatigue leads to poor food choices 73% of the time.",
  "Try apple cider vinegar before a carb-heavy meal. It can reduce blood sugar response by 34%.",
  "Dance for 5 minutes to your favorite song. It's a mood booster AND a metabolism activator.",
  "Eat berries today. Anthocyanins in berries improve insulin sensitivity and reduce fat storage.",
  "Practice 4-7-8 breathing: inhale 4 sec, hold 7 sec, exhale 8 sec. Do it 3 times to calm your nervous system.",
  "Eat dinner by 7 PM tonight. Early dinners improve overnight fat burning by extending your natural fast.",
  "Add turmeric to your eggs or soup. Just 1/4 tsp with black pepper fights inflammation all day.",
  "Try 'box breathing' during a stressful moment: 4 sec in, 4 sec hold, 4 sec out, 4 sec hold. Repeat 4 times.",
  "Soak in an Epsom salt bath tonight. Magnesium absorbs through your skin and reduces cortisol.",
  "Start your meal with a small salad. The fiber creates a 'bed' that slows sugar absorption from the rest of your food.",
  "Visualize your goal body for 2 minutes. Neuroplasticity research shows visualization activates the same neural pathways as physical action.",
  "Eat eggs for breakfast — the protein and choline keep you full until lunch and support liver detox.",
  "Try the 'half-plate rule': fill half your plate with vegetables at every meal.",
  "Place your hand on your heart and take 3 slow breaths. Heart-focused breathing reduces anxiety hormones within 60 seconds.",
  "Snack on celery with almond butter. Celery is a natural diuretic that reduces water retention.",
  "Walk backward for 2 minutes (safely). It activates different muscle groups and improves balance and knee health.",
  "Add lemon to your water all day. The citric acid supports liver detoxification pathways.",
  "Eat your meals without screens. Distracted eating increases calorie intake by up to 25%.",
  "Try oil pulling: swish 1 tbsp coconut oil in your mouth for 5 minutes. It pulls toxins and improves oral microbiome.",
  "Read a page of something inspiring before bed instead of scrolling. Lower cortisol = better sleep = more fat burning.",
  "Do 30 seconds of jumping jacks right now. Quick bursts of activity increase EPOC (after-burn) for hours.",
];

const MEAL_RECIPES = [
  { title: "Mediterranean Egg Scramble", desc: "2 eggs scrambled with spinach, cherry tomatoes, feta, and oregano. Serve with 1/2 avocado.", category: "Breakfast" },
  { title: "Tropical Anti-Bloat Smoothie", desc: "Blend 1 cup pineapple, 1/2 cucumber, handful of mint, 1 cup coconut water, and 1 tbsp chia seeds.", category: "Breakfast" },
  { title: "Protein Overnight Oats", desc: "1/3 cup oats + 1 scoop protein powder + almond milk + 1 tbsp almond butter. Refrigerate overnight.", category: "Breakfast" },
  { title: "Avocado Toast with Seeds", desc: "Whole grain toast topped with mashed avocado, everything seasoning, hemp seeds, and a poached egg.", category: "Breakfast" },
  { title: "Berry Yogurt Parfait", desc: "Greek yogurt layered with mixed berries, 1 tbsp ground flaxseed, and a drizzle of raw honey.", category: "Breakfast" },
  { title: "Sweet Potato Hash", desc: "Diced sweet potato pan-fried with bell pepper, onion, and 2 eggs. Season with paprika and cumin.", category: "Breakfast" },
  { title: "Banana Walnut Smoothie", desc: "Blend 1 banana, 1 cup almond milk, 1 tbsp walnut butter, 1/2 tsp cinnamon, and ice.", category: "Breakfast" },
  { title: "Coconut Chia Bowl", desc: "3 tbsp chia seeds in coconut milk overnight. Top with mango, toasted coconut flakes, and macadamia nuts.", category: "Breakfast" },
  { title: "Smoked Salmon Plate", desc: "Smoked salmon with cream cheese, cucumber slices, capers, and a squeeze of lemon. Pair with whole grain crackers.", category: "Breakfast" },
  { title: "Turmeric Veggie Frittata", desc: "Whisk 3 eggs with turmeric, black pepper, mushrooms, and zucchini. Bake at 375°F for 20 min.", category: "Breakfast" },
  { title: "Thai Peanut Chicken Salad", desc: "Grilled chicken over mixed greens with cucumber, shredded carrot, cilantro, and peanut-lime dressing.", category: "Lunch" },
  { title: "Lentil Power Bowl", desc: "1 cup cooked lentils + roasted sweet potato + arugula + tahini drizzle + pumpkin seeds.", category: "Lunch" },
  { title: "Zucchini Noodle Pad Thai", desc: "Spiralized zucchini stir-fried with shrimp, bean sprouts, lime, and a light almond butter sauce.", category: "Lunch" },
  { title: "Greek Quinoa Bowl", desc: "Quinoa + cucumber + cherry tomatoes + kalamata olives + red onion + feta + lemon-olive oil dressing.", category: "Lunch" },
  { title: "Chicken Avocado Wrap", desc: "Whole wheat wrap with grilled chicken, avocado, lettuce, tomato, and a drizzle of Greek yogurt ranch.", category: "Lunch" },
  { title: "Immune-Boosting Miso Soup", desc: "White miso paste dissolved in warm water with tofu cubes, seaweed, green onion, and ginger.", category: "Lunch" },
  { title: "Salmon Poke Bowl", desc: "Diced raw salmon (or smoked) over brown rice with avocado, edamame, cucumber, and soy-ginger sauce.", category: "Lunch" },
  { title: "Roasted Beet & Goat Cheese Salad", desc: "Roasted beets on arugula with goat cheese, walnuts, and balsamic glaze. Add grilled chicken for protein.", category: "Lunch" },
  { title: "Black Bean Taco Bowl", desc: "Black beans, brown rice, corn, pico de gallo, avocado, and a squeeze of lime. Skip the tortilla.", category: "Lunch" },
  { title: "Stuffed Bell Pepper", desc: "Bell pepper filled with ground turkey, cauliflower rice, tomato sauce, and topped with mozzarella. Bake 25 min.", category: "Lunch" },
  { title: "Herb-Crusted Salmon", desc: "Salmon fillet coated with Dijon mustard, fresh dill, and crushed walnuts. Bake 18 min at 400°F. Serve with asparagus.", category: "Dinner" },
  { title: "Slow Cooker Chicken Curry", desc: "Chicken thighs in coconut milk with turmeric, cumin, ginger, and garlic. Serve over cauliflower rice.", category: "Dinner" },
  { title: "Lemon Garlic Shrimp", desc: "Sauté shrimp with garlic, lemon, butter, and red pepper flakes. Serve over zucchini noodles with fresh parsley.", category: "Dinner" },
  { title: "Turkey Meatball Soup", desc: "Turkey meatballs in bone broth with kale, carrots, celery, and Italian herbs. Comfort food that heals your gut.", category: "Dinner" },
  { title: "Balsamic Glazed Chicken", desc: "Chicken breast glazed with balsamic vinegar and honey. Roast with Brussels sprouts and sweet potato wedges.", category: "Dinner" },
  { title: "Cauliflower Steak", desc: "Thick cauliflower slice roasted with olive oil, smoked paprika, and garlic. Top with chimichurri sauce.", category: "Dinner" },
  { title: "One-Pan Mediterranean Cod", desc: "Cod fillet baked with cherry tomatoes, olives, capers, and artichoke hearts. Drizzle with olive oil.", category: "Dinner" },
  { title: "Ginger Beef Stir-Fry", desc: "Lean beef strips with broccoli, snap peas, and bell pepper in a ginger-garlic-soy sauce. Serve over brown rice.", category: "Dinner" },
  { title: "Stuffed Portobello Mushrooms", desc: "Portobello caps filled with spinach, sun-dried tomatoes, goat cheese, and pine nuts. Bake 20 min.", category: "Dinner" },
  { title: "Coconut Lime Chicken", desc: "Chicken simmered in coconut milk, lime juice, cilantro, and Thai basil. Serve with jasmine rice.", category: "Dinner" },
  { title: "Cucumber Hummus Bites", desc: "Thick cucumber rounds topped with hummus, cherry tomato, and a sprinkle of za'atar.", category: "Snack" },
  { title: "Apple Cinnamon Chips", desc: "Slice an apple paper-thin, dust with cinnamon, and bake at 225°F for 1.5 hours until crisp.", category: "Snack" },
  { title: "Almond Butter Banana Roll", desc: "Spread almond butter on a banana, roll in crushed dark chocolate and coconut flakes. Slice into rounds.", category: "Snack" },
  { title: "Roasted Chickpeas", desc: "Rinse canned chickpeas, toss with olive oil and smoked paprika. Roast at 400°F for 30 min until crunchy.", category: "Snack" },
  { title: "Frozen Yogurt Bark", desc: "Spread Greek yogurt on parchment, top with berries and granola. Freeze 2 hours, break into pieces.", category: "Snack" },
  { title: "Turmeric Latte Energy Balls", desc: "Blend dates, cashews, turmeric, coconut oil, and vanilla. Roll into balls and refrigerate.", category: "Snack" },
  { title: "Stuffed Dates", desc: "Medjool dates filled with almond butter and a pinch of sea salt. 2-3 dates = perfect afternoon pick-me-up.", category: "Snack" },
  { title: "Avocado Chocolate Mousse", desc: "Blend 1 ripe avocado with 2 tbsp cacao powder, 1 tbsp honey, and a splash of almond milk until silky.", category: "Snack" },
  { title: "Seed Crackers", desc: "Mix chia, flax, sunflower, and pumpkin seeds with water. Spread thin on parchment, bake at 325°F for 30 min.", category: "Snack" },
  { title: "Frozen Berry Bites", desc: "Dip fresh berries in dark chocolate. Freeze for 1 hour. A guilt-free sweet treat.", category: "Snack" },
];

const WELLNESS_CHALLENGES = [
  { title: "Digital Sunset", desc: "Turn off all screens 1 hour before bed. Read, journal, or stretch instead. Your melatonin production will skyrocket.", icon: "📵" },
  { title: "Gratitude Walk", desc: "Take a 15-minute walk and name 10 things you're grateful for — out loud. Gratitude + movement = cortisol crusher.", icon: "🚶" },
  { title: "Cold Shower Finish", desc: "End your shower with 60 seconds of cold water. Focus on breathing deeply. This activates brown fat and boosts mood.", icon: "🚿" },
  { title: "Meal Prep Sunday", desc: "Prep 3 meals for this week. Wash, chop, and store vegetables. Cook a protein. Having food ready prevents bad choices.", icon: "🥗" },
  { title: "5-Minute Meditation", desc: "Sit quietly with your eyes closed. Focus only on your breath for 5 minutes. If your mind wanders, gently return to the breath.", icon: "🧘" },
  { title: "Drink 100oz of Water", desc: "Challenge yourself to drink 100oz of water today. Add lemon, cucumber, or mint for flavor. Track with rubber bands on your bottle.", icon: "💧" },
  { title: "No Sugar Day", desc: "Avoid all added sugar today — read labels carefully. Natural sugars from whole fruit are okay. Notice how your energy stabilizes.", icon: "🍬" },
  { title: "10,000 Steps", desc: "Hit 10K steps today. Take walking meetings, park farther away, or add an evening stroll. Movement is medicine.", icon: "👟" },
  { title: "Stretch & Flow", desc: "Do 10 minutes of gentle stretching or yoga. Focus on hips, shoulders, and hamstrings — where stress accumulates.", icon: "🤸" },
  { title: "Cook Something New", desc: "Try a recipe you've never made. The novelty activates dopamine pathways — the healthy kind that doesn't need sugar.", icon: "👩‍🍳" },
  { title: "Social Media Fast", desc: "Stay off social media for 24 hours. Comparison is the thief of joy — and a cortisol trigger. Be present in YOUR life.", icon: "📱" },
  { title: "Deep Sleep Protocol", desc: "Tonight: room at 67°F, no screens after 9 PM, chamomile tea, 4-7-8 breathing. Track how you feel tomorrow morning.", icon: "😴" },
  { title: "Random Act of Kindness", desc: "Do something kind for a stranger today. Helping others releases oxytocin, which reduces cortisol and inflammation.", icon: "💝" },
  { title: "Nature Therapy", desc: "Spend 20 minutes in nature — a park, garden, or even your backyard. Forest bathing reduces cortisol by 16% in just 15 minutes.", icon: "🌳" },
  { title: "Body Scan Before Bed", desc: "Lie down and mentally scan from toes to head, relaxing each muscle group. This progressive relaxation improves sleep quality 40%.", icon: "🛌" },
  { title: "Dry Brushing Ritual", desc: "Before your shower, use a natural bristle brush in upward strokes toward the heart. Boosts circulation, reduces cellulite.", icon: "✨" },
  { title: "Protein at Every Meal", desc: "Ensure each meal has at least 20g of protein. Track it today. Protein is the #1 macronutrient for fat loss and muscle tone.", icon: "🥩" },
  { title: "Posture Check", desc: "Set 5 alarms today. Each time, check your posture — shoulders back, chin level, core engaged. Better posture = better breathing = less stress.", icon: "🏋️" },
  { title: "Write a Letter to Future You", desc: "Write a letter to yourself 6 months from now. Describe how you feel, what you've achieved. Seal it and set a reminder to open it.", icon: "✉️" },
  { title: "Declutter One Space", desc: "Clean one drawer, shelf, or corner. External clutter raises cortisol. A tidy space = a calmer mind = less emotional eating.", icon: "🧹" },
  { title: "Epsom Salt Bath", desc: "Soak in a warm bath with 2 cups of Epsom salt for 20 minutes. The magnesium absorbs through skin and melts tension.", icon: "🛁" },
  { title: "Power Playlist Walk", desc: "Make a playlist of songs that make you feel unstoppable. Walk briskly for the entire playlist. Movement + music = endorphin explosion.", icon: "🎵" },
  { title: "Veggie-Only Dinner", desc: "Tonight, eat a dinner with zero animal products. Load up on roasted vegetables, legumes, and healthy fats.", icon: "🥦" },
  { title: "Journal Your Why", desc: "Write for 5 minutes about WHY you started this. What does your healthiest self look like? Feel like? Do? This clarity fuels consistency.", icon: "📝" },
  { title: "Sunrise Reset", desc: "Wake up 15 minutes earlier and watch the sunrise (or simply sit with morning light). It calibrates your circadian clock for the day.", icon: "🌅" },
  { title: "Belly Breathing", desc: "Place one hand on your chest, one on your belly. Breathe so only the belly hand moves. Do this for 3 minutes. It activates fat-burning mode.", icon: "🫁" },
  { title: "Eat Without Distractions", desc: "No phone, no TV, no reading during meals today. Just you and your food. Mindful eating reduces intake by 20%.", icon: "🍽️" },
  { title: "Walking Meeting", desc: "If you have a phone call or meeting today, do it walking. Motion improves creativity by 60% (Stanford study).", icon: "📞" },
  { title: "Try a New Tea", desc: "Buy or brew a tea you've never tried. Explore flavors — hibiscus, rooibos, jasmine, lemongrass. Expanding your palate supports gut diversity.", icon: "🍵" },
  { title: "Celebrate Yourself", desc: "Look in the mirror and name 3 things your body does well. Appreciation accelerates transformation — criticism slows it down.", icon: "🪞" },
];

export const getExtendedPhase = (day) => {
  if (day <= 60) return EXTENDED_PHASES[0];
  if (day <= 90) return EXTENDED_PHASES[1];
  if (day <= 120) return EXTENDED_PHASES[2];
  if (day <= 150) return EXTENDED_PHASES[3];
  if (day <= 180) return EXTENDED_PHASES[4];
  return EXTENDED_PHASES[5];
};

export const getExtendedDayContent = (day) => {
  const adjustedDay = day - 31;
  const shotIndex = adjustedDay % MORNING_SHOTS.length;
  const tipIndex = (adjustedDay * 7 + 3) % DAILY_TIPS.length;
  const mealIndex = (adjustedDay * 3 + 11) % MEAL_RECIPES.length;
  const challengeIndex = (adjustedDay * 5 + 2) % WELLNESS_CHALLENGES.length;

  return {
    phase: getExtendedPhase(day),
    shot: MORNING_SHOTS[shotIndex],
    tip: DAILY_TIPS[tipIndex],
    meal: MEAL_RECIPES[mealIndex],
    challenge: WELLNESS_CHALLENGES[challengeIndex],
  };
};

export { EXTENDED_PHASES };
