export const GUT_PHASES = [
  { id: 1, name: "Gut Reset", range: "Days 1-7", icon: "🧹", color: "from-red-500 to-orange-500", desc: "Strip away harmful bacteria, reduce inflammation, and prepare your gut for rebuilding." },
  { id: 2, name: "Microbiome Rebuilding", range: "Days 8-21", icon: "🦠", color: "from-green-500 to-emerald-600", desc: "Repopulate your gut with beneficial bacteria using fermented foods and targeted prebiotics." },
  { id: 3, name: "Metabolism Acceleration", range: "Days 22-45", icon: "🔥", color: "from-orange-500 to-amber-600", desc: "Activate thermogenic pathways, introduce intermittent fasting, and supercharge fat oxidation." },
  { id: 4, name: "Maintenance & Optimization", range: "Days 46-60", icon: "⚡", color: "from-violet-500 to-purple-600", desc: "Lock in your microbiome gains and fine-tune your gut-brain axis for permanent results." },
];

const MORNING_PROTOCOLS = [
  "1 tbsp apple cider vinegar + 1/4 tsp ginger powder in 8oz warm water. Drink 20 min before breakfast.",
  "1/2 tsp baking soda + juice of 1/2 lemon in 8oz warm water. Sip slowly on empty stomach.",
  "Bone broth (1 cup) with 1/4 tsp turmeric and a pinch of black pepper. Sip like tea.",
  "Ginger-lemon shot: juice of 1 lemon + 1 inch fresh ginger blended in 4oz water. Down it fast.",
  "1 tbsp aloe vera juice + 8oz room temperature water. Soothes and repairs the gut lining.",
  "Fennel seed tea: 1 tsp crushed fennel steeped 8 min. Reduces gas and bloating within 30 min.",
  "1 tbsp chia seeds soaked 10 min in warm lemon water. Acts as an internal scrubber.",
  "Peppermint + chamomile tea blend — steep 5 min. Calms the enteric nervous system.",
  "1/4 tsp L-glutamine powder + 8oz water. The #1 amino acid for gut wall repair.",
  "Slippery elm bark tea: 1 tsp powder mixed into warm water. Creates a protective coating.",
  "Warm water + 1 tbsp raw honey + 1/4 tsp cinnamon. Antimicrobial and prebiotic.",
  "Dandelion root coffee: steep 1 tbsp roasted dandelion root 10 min. Supports bile flow.",
  "1 tbsp flaxseed meal + 8oz warm water + squeeze of lemon. Gentle fiber detox.",
  "Marshmallow root tea: steep 1 tsp for 10 min. Coats and heals the digestive tract.",
  "Licorice root tea (DGL form): steep 5 min. Repairs stomach lining without side effects.",
  "Moringa tea: 1/2 tsp moringa powder in hot water + lemon. 46 antioxidants in one cup.",
  "Triphala tea: 1/2 tsp triphala powder in warm water. Ancient Ayurvedic gut cleanser.",
  "Warm water + 1 tbsp coconut oil + pinch of Himalayan salt. Lubricates the intestines.",
  "Nettle leaf tea steeped 10 min. Mineral-rich, anti-inflammatory, and alkalizing.",
  "Probiotic shot: 2oz sauerkraut juice on empty stomach. More potent than most capsules.",
  "Ginger-turmeric-black pepper shot in 4oz warm water. Triple anti-inflammatory combo.",
  "Psyllium husk: 1 tsp in 8oz water, drink immediately before it gels. Gentle bulk fiber.",
  "Cacao + reishi blend: 1 tsp raw cacao + 1/2 tsp reishi powder in warm water.",
  "Apple cider vinegar + raw honey + warm water. The classic gut-healing trifecta.",
  "Digestive bitters: 5 drops in 4oz water before eating. Stimulates stomach acid naturally.",
  "Cabbage juice shot: 2oz fresh cabbage juice. Contains L-glutamine naturally.",
  "Hibiscus + rosehip tea blend. Rich in vitamin C, supports collagen for gut lining.",
  "Celery juice: 4oz fresh celery juice on empty stomach. Rebuilds HCl production.",
  "1/4 tsp activated charcoal in 8oz water. Binds toxins (take 2hrs away from meds).",
  "Chicory root coffee: natural prebiotic that feeds Bifidobacteria specifically.",
];

const EVENING_PROTOCOLS = [
  "Chamomile + valerian root tea 30 min before bed. Activates parasympathetic digestion mode.",
  "Golden milk: warm almond milk + 1/4 tsp turmeric + cinnamon + black pepper. Anti-inflammatory nightcap.",
  "Magnesium glycinate: 200mg with warm water. Relaxes gut muscles and promotes motility.",
  "Warm bone broth with a pinch of sea salt. Collagen repairs gut lining overnight.",
  "Peppermint tea after dinner. Relaxes the lower esophageal sphincter and reduces bloating.",
  "1 tbsp apple cider vinegar in 4oz warm water after your last meal. Aids overnight digestion.",
  "Passionflower tea steeped 7 min. Calms gut-brain axis anxiety that disrupts digestion.",
  "Warm water with 1 tbsp raw honey. Feeds beneficial gut bacteria while you sleep.",
  "Lemon balm tea: steep 5 min. Reduces gas, cramping, and nervous stomach.",
  "Probiotic-rich kefir: 4oz plain kefir as evening snack. 30+ strains of beneficial bacteria.",
  "Tart cherry juice: 2oz. Natural melatonin source + anti-inflammatory for the gut.",
  "Ginger tea with a splash of coconut milk. Warms the digestive fire for overnight repair.",
  "1/4 tsp ashwagandha in warm milk. Lowers cortisol which directly irritates the gut lining.",
  "Cinnamon tea: 1 stick steeped 10 min. Regulates blood sugar to prevent overnight fat storage.",
  "Slippery elm + honey in warm water. Creates a protective film over the intestinal wall.",
  "Holy basil (tulsi) tea. Adaptogenic herb that normalizes gut pH and reduces acid reflux.",
  "Warm water + 1 tbsp ground flaxseed. Omega-3s reduce gut inflammation overnight.",
  "Aloe vera juice: 1 tbsp before bed. Soothes any inflammation from the day's meals.",
  "Lavender + chamomile tea. The combination synergistically calms the enteric nervous system.",
  "Coconut water + pinch of sea salt. Rehydrates and provides electrolytes for gut function.",
  "Rooibos tea with vanilla. Antispasmodic properties reduce nighttime cramping.",
  "Warm water + 2 tbsp collagen peptides. Direct building blocks for gut lining repair.",
  "Fennel + caraway seed tea. Traditional European remedy for digestive discomfort.",
  "Miso soup: 1 cup warm miso with scallions. Living enzymes support overnight digestion.",
  "Cardamom + ginger tea. Stimulates digestive enzymes and reduces overnight acid reflux.",
  "1 tbsp MCT oil in warm water. Short-chain fats feed colonocytes (gut wall cells).",
  "Licorice + peppermint blend tea. Dual-action: repair and soothe simultaneously.",
  "Warm turmeric water + 1/2 tsp coconut oil. Fat helps absorb curcumin 7x better.",
  "Prune juice: 2oz warm. Natural prebiotic that promotes morning regularity.",
  "Reishi mushroom tea: 1/2 tsp reishi powder steeped. Immunomodulating and gut-healing.",
];

const GUT_RECIPES = [
  { title: "Probiotic Power Bowl", desc: "Brown rice + kimchi + soft-boiled egg + avocado + sesame seeds + nori strips. Drizzle with tamari.", category: "Lunch", time: "15 min" },
  { title: "Gut-Healing Bone Broth Ramen", desc: "Bone broth base with zucchini noodles, shiitake mushrooms, bok choy, soft egg, and ginger.", category: "Dinner", time: "20 min" },
  { title: "Fermented Veggie Wrap", desc: "Coconut wrap filled with sauerkraut, avocado, sprouts, cucumber, and tahini drizzle.", category: "Lunch", time: "10 min" },
  { title: "Anti-Bloat Smoothie", desc: "Papaya + pineapple + ginger + mint + coconut water. Enzymes that dissolve bloating.", category: "Breakfast", time: "5 min" },
  { title: "Prebiotic Garlic Shrimp", desc: "Shrimp sautéed with 6 cloves garlic, asparagus, and artichoke hearts in olive oil.", category: "Dinner", time: "15 min" },
  { title: "Kefir Overnight Oats", desc: "Oats soaked in kefir overnight + banana + walnuts + cinnamon + drizzle of honey.", category: "Breakfast", time: "5 min prep" },
  { title: "Miso-Glazed Salmon", desc: "Salmon marinated in white miso, mirin, and ginger. Broil 8 min. Serve with steamed bok choy.", category: "Dinner", time: "25 min" },
  { title: "Jerusalem Artichoke Soup", desc: "Roasted sunchokes blended with onion, garlic, thyme, and bone broth. Top with pumpkin seeds.", category: "Lunch", time: "30 min" },
  { title: "Tempeh Buddha Bowl", desc: "Marinated tempeh + quinoa + roasted sweet potato + kale + tahini-lemon dressing.", category: "Lunch", time: "25 min" },
  { title: "Collagen Berry Smoothie", desc: "Mixed berries + collagen peptides + spinach + almond milk + 1 tbsp ground flaxseed.", category: "Breakfast", time: "5 min" },
  { title: "Sauerkraut & Turkey Plate", desc: "Sliced turkey breast with raw sauerkraut, cucumber, mustard, and whole grain crackers.", category: "Lunch", time: "5 min" },
  { title: "Turmeric Cauliflower Steak", desc: "Thick cauliflower slices rubbed with turmeric, cumin, and olive oil. Roast 25 min at 425°F.", category: "Dinner", time: "30 min" },
  { title: "Kombucha Chia Pudding", desc: "Chia seeds soaked in kombucha overnight. Top with berries and toasted coconut.", category: "Breakfast", time: "5 min prep" },
  { title: "Leek & Potato Soup", desc: "Leeks (prebiotic) simmered with potato, garlic, and bone broth. Blend smooth. Top with chives.", category: "Dinner", time: "25 min" },
  { title: "Yogurt Parfait Supreme", desc: "Greek yogurt + granola + mixed berries + ground flaxseed + drizzle of raw honey + bee pollen.", category: "Breakfast", time: "5 min" },
  { title: "Gut-Friendly Tacos", desc: "Soft corn tortillas with black beans, pickled onions, avocado, cilantro, and lime crema.", category: "Dinner", time: "20 min" },
  { title: "Dandelion Green Salad", desc: "Dandelion greens + arugula + shaved parmesan + walnuts + lemon-olive oil dressing.", category: "Lunch", time: "10 min" },
  { title: "Overnight Miso Oats", desc: "Oats soaked in warm miso broth overnight. Top with a soft egg, scallions, and sesame oil.", category: "Breakfast", time: "5 min prep" },
  { title: "Chicken Congee", desc: "Rice porridge slow-cooked with chicken, ginger, garlic, and bone broth. Top with scallions.", category: "Dinner", time: "40 min" },
  { title: "Enzyme-Rich Fruit Plate", desc: "Papaya + pineapple + kiwi + mango. All contain natural digestive enzymes.", category: "Snack", time: "5 min" },
  { title: "Kimchi Fried Rice", desc: "Day-old brown rice stir-fried with kimchi, egg, sesame oil, and green onions.", category: "Lunch", time: "10 min" },
  { title: "Coconut Yogurt Bowl", desc: "Coconut yogurt + passion fruit + macadamia nuts + hemp seeds + raw honey.", category: "Breakfast", time: "5 min" },
  { title: "Stuffed Zucchini Boats", desc: "Zucchini halves filled with ground turkey, diced tomatoes, herbs, and topped with goat cheese.", category: "Dinner", time: "30 min" },
  { title: "Apple Cider Vinegar Slaw", desc: "Shredded cabbage + carrots + ACV + olive oil + celery seeds + honey. Ferments slightly as it sits.", category: "Side", time: "10 min" },
  { title: "Ginger Carrot Soup", desc: "Roasted carrots blended with fresh ginger, coconut milk, and a pinch of cayenne.", category: "Lunch", time: "25 min" },
  { title: "Probiotic Smoothie Bowl", desc: "Kefir + frozen açai + banana blended thick. Top with granola, coconut, and goji berries.", category: "Breakfast", time: "5 min" },
  { title: "Lentil & Turmeric Stew", desc: "Red lentils simmered with turmeric, cumin, tomatoes, spinach, and coconut milk.", category: "Dinner", time: "25 min" },
  { title: "Pickled Veggie Snack Plate", desc: "Pickled cucumbers + carrots + radishes + hummus + olives. Quick probiotic-rich snack.", category: "Snack", time: "5 min" },
  { title: "Mushroom & Barley Soup", desc: "Mixed mushrooms + pearl barley + onion + celery + thyme in bone broth. Simmer 30 min.", category: "Dinner", time: "35 min" },
  { title: "Banana Walnut Kefir Shake", desc: "Kefir + banana + walnuts + cinnamon + vanilla blended smooth. Prebiotic + probiotic combo.", category: "Breakfast", time: "5 min" },
];

const GI_SYMPTOMS = [
  { id: "bloating", label: "Bloating", icon: "🫧" },
  { id: "gas", label: "Gas", icon: "💨" },
  { id: "cramping", label: "Cramping", icon: "😣" },
  { id: "constipation", label: "Constipation", icon: "🧱" },
  { id: "diarrhea", label: "Loose Stool", icon: "💧" },
  { id: "heartburn", label: "Heartburn", icon: "🔥" },
  { id: "nausea", label: "Nausea", icon: "🤢" },
  { id: "energy_low", label: "Low Energy", icon: "🪫" },
  { id: "brain_fog", label: "Brain Fog", icon: "🌫️" },
  { id: "skin_issues", label: "Skin Issues", icon: "🔴" },
];

const DAILY_TIPS = [
  "Chew each bite 25-30 times. Digestion starts in the mouth — saliva contains amylase that breaks down starches. Poor chewing = poor digestion.",
  "Stop drinking water 15 min before meals and wait 30 min after. Excess water during meals dilutes stomach acid and digestive enzymes.",
  "Eat your meals sitting down, without screens, in a relaxed state. Stress activates 'fight or flight' which shuts down digestive function.",
  "Take 3 deep belly breaths before each meal. This activates the vagus nerve and switches on 'rest and digest' mode.",
  "Add a small salad before your main meal. Raw vegetables stimulate digestive enzyme production and create a fiber bed for slower glucose absorption.",
  "Eat prebiotic foods today: garlic, onions, leeks, asparagus, or bananas. These feed your good bacteria specifically.",
  "Avoid eating raw food after 4 PM. Your digestive fire weakens in the evening — cooked food is easier to process.",
  "Try 'food combining' today: eat fruit alone (not with meals), and don't mix heavy starches with heavy proteins in the same meal.",
  "Walk for 10-15 minutes after your largest meal. Gentle movement increases gastric motility by 30% and reduces bloating.",
  "Track your fiber intake today. Aim for 25-30g. Increase slowly — too fast causes gas. Most Americans only get 15g.",
  "Soak your grains, nuts, and seeds overnight. This neutralizes phytic acid and enzyme inhibitors that cause digestive distress.",
  "Add bitter foods to your diet today: arugula, endive, radicchio, or dandelion greens. Bitters stimulate bile and digestive juices.",
  "Avoid ice-cold drinks today. Cold constricts blood vessels in the stomach, slowing digestion. Room temp or warm is better.",
  "Try eating your largest meal at lunch, not dinner. Your digestive system is strongest between 10 AM and 2 PM (following circadian rhythms).",
  "Include healthy fats with every meal: olive oil, avocado, nuts. Fat stimulates CCK (cholecystokinin) which signals fullness and slows gastric emptying.",
  "Avoid processed sugar today. Sugar feeds pathogenic bacteria like Candida and disrupts your microbiome balance within hours.",
  "Eat a variety of 30 different plant foods this week. Diversity = microbiome diversity = better immunity and digestion.",
  "Massage your abdomen in clockwise circles for 3 minutes after eating. This follows the natural path of your colon.",
  "Cook with bone broth instead of water when making rice, quinoa, or soups. Sneaky way to get more collagen and gut-healing amino acids.",
  "Practice the 'pause and assess' method: halfway through your plate, stop for 2 minutes. Are you actually still hungry? Most times, you're not.",
  "Eat fermented food with at least one meal today. Options: yogurt, kefir, sauerkraut, kimchi, miso, tempeh, or kombucha.",
  "Avoid artificial sweeteners today (sucralose, aspartame, saccharin). Studies show they destroy gut bacteria even at low doses.",
  "Eat your meals at consistent times. Your gut has its own circadian rhythm — irregular eating disrupts enzyme production.",
  "Add ginger to your cooking. Gingerol increases gastric motility by 50% and reduces nausea naturally.",
  "Reduce your antibiotic-raised meat intake. Switch to organic/grass-fed when possible — antibiotics in meat disrupt YOUR microbiome.",
  "Try 'mono-eating' for one meal: eat only one type of food. This gives your digestive system a simple, easy-to-process meal.",
  "Include resistant starch today: cooled potato, cooled rice, green banana, or plantain. These feed your butyrate-producing bacteria.",
  "Avoid alcohol today. Even moderate alcohol kills beneficial bacteria and increases intestinal permeability ('leaky gut') within hours.",
  "Do a 12-hour overnight fast. Stop eating by 8 PM, don't eat until 8 AM. This allows your 'migrating motor complex' to clean your intestines.",
  "Add apple cider vinegar to your salad dressing. Getting ACV through food is gentler than drinking it straight and still supports digestion.",
  "Eat slowly and mindfully. It takes 20 minutes for stretch receptors in your stomach to signal your brain that you're full.",
  "Include zinc-rich foods today: pumpkin seeds, chickpeas, or dark chocolate. Zinc is essential for gut lining repair.",
  "Avoid NSAID pain relievers (ibuprofen, aspirin) when possible. They damage the gut lining and increase intestinal permeability.",
  "Try a tablespoon of raw honey. It contains oligosaccharides that feed Bifidobacteria — your gut's best friends.",
  "Eat the skin of your fruits and vegetables when possible. The skin contains most of the prebiotic fiber your gut bacteria crave.",
  "Notice which foods make you bloated and keep a simple food diary. Identifying your personal triggers is more powerful than any generic protocol.",
  "Include polyphenol-rich foods: berries, dark chocolate, green tea, red grapes. Polyphenols are jet fuel for beneficial bacteria.",
  "Reduce emulsifier intake: check labels for polysorbate 80, carboxymethylcellulose. These additives destroy the mucus layer in your gut.",
  "Eat slowly enough that you could describe the taste, texture, and temperature of each bite if asked. This level of awareness transforms digestion.",
  "Drink warm water with lemon first thing in the morning. The citric acid mimics digestive acids and jumpstarts your system.",
  "Include omega-3 rich foods today: salmon, sardines, walnuts, or flaxseeds. Omega-3s reduce gut inflammation at the cellular level.",
  "Try tongue scraping in the morning before brushing. Removes overnight bacterial buildup that would otherwise be swallowed into your gut.",
  "Stand up and do 5 gentle torso twists after eating. Rotation massages the internal organs and promotes motility.",
  "Eat cruciferous vegetables today: broccoli, cauliflower, Brussels sprouts, kale. Sulforaphane in these repairs gut lining cells.",
  "Limit caffeine to 1-2 cups before noon. Excess caffeine increases gut motility too much and can irritate the intestinal lining.",
  "Include coconut products today (oil, milk, or flakes). Lauric acid in coconut is antimicrobial against harmful gut bacteria.",
  "Swap table salt for Himalayan pink salt. The 84 trace minerals support digestive enzyme production.",
  "End your shower with 30 seconds of cold water on your abdomen. Cold exposure activates the vagus nerve which improves gut function.",
  "Practice gratitude before meals. Positive emotional states improve vagal tone and digestive capacity measurably.",
  "Make homemade bone broth this weekend. Simmer bones 12-24 hours with ACV (helps extract minerals). Freeze in ice cube trays for easy use.",
  "Add turmeric + black pepper to scrambled eggs. Piperine increases curcumin absorption by 2,000% and both heal the gut.",
  "Try 'sequential eating': eat vegetables first, then protein, then carbs. This reduces glucose spikes by up to 73% (Stanford study).",
  "Include mushrooms in your diet today. Beta-glucans in mushrooms feed beneficial gut bacteria and modulate the immune system.",
  "Avoid eating when angry, stressed, or rushing. Emotional states directly impact stomach acid production and enzyme secretion.",
  "Try a spoonful of unpasteurized sauerkraut before each meal this week. It's the cheapest, most effective probiotic you can buy.",
  "Include adequate protein at every meal (20-30g). Amino acids are the raw materials your gut uses to rebuild its lining every 3-5 days.",
  "Drink herbal tea instead of snacking between meals. Many between-meal cravings are actually thirst or boredom, not hunger.",
  "Notice your posture while eating. Slouching compresses your digestive organs. Sit upright to allow proper food passage.",
  "Cook with herbs today: oregano, thyme, basil, rosemary. These Mediterranean herbs have powerful antimicrobial and carminative properties.",
  "Get 15 minutes of morning sunlight. UV light on the skin increases vitamin D production, which modulates gut immune function.",
];

const CELLULITE_EXERCISES = [
  { title: "Dry Brushing Protocol", desc: "Use a natural bristle brush. Start at feet, brush upward in long strokes toward the heart. Cover entire body. 5 minutes.", target: "Full body", time: "5 min" },
  { title: "Foam Rolling Thighs", desc: "Lie face down on a foam roller at your thighs. Roll from hips to knees slowly, pausing on tender spots for 20 seconds.", target: "Thighs", time: "3 min" },
  { title: "Glute Bridge Pulses", desc: "Lie on back, feet flat. Lift hips high, squeeze glutes at top. Pulse 20 times, hold 10 sec, repeat 3 sets.", target: "Glutes & thighs", time: "5 min" },
  { title: "Wall Sit Hold", desc: "Back against wall, slide down until thighs are parallel to floor. Hold 30-60 seconds. Rest 30 sec. Repeat 3 times.", target: "Quads & glutes", time: "4 min" },
  { title: "Sumo Squats", desc: "Wide stance, toes turned out 45°. Squat deep, pressing knees out. 15 reps x 3 sets. Add a pulse at the bottom.", target: "Inner thighs & glutes", time: "5 min" },
  { title: "Donkey Kicks", desc: "On hands and knees, kick one leg back and up, squeezing glute at top. 20 per leg x 3 sets.", target: "Glutes", time: "6 min" },
  { title: "Fire Hydrants", desc: "On hands and knees, lift knee out to side while keeping 90° bend. 20 per side x 3 sets. Squeeze at top.", target: "Outer thighs & hips", time: "6 min" },
  { title: "Step-Ups", desc: "Step onto a sturdy chair or bench, driving through the heel. 15 per leg x 3 sets. Keep core tight.", target: "Quads & glutes", time: "8 min" },
  { title: "Coffee Scrub Massage", desc: "Mix used coffee grounds + coconut oil. Massage into cellulite areas in firm circular motions for 5 min before shower.", target: "Problem areas", time: "5 min" },
  { title: "Curtsy Lunges", desc: "Step one foot behind and across, lowering into a curtsy. 12 per side x 3 sets. Keep front knee over ankle.", target: "Outer glutes & thighs", time: "6 min" },
  { title: "Calf Raises", desc: "Stand on edge of a step, heels hanging off. Rise up on toes, hold 2 sec, lower below step level. 20 reps x 3 sets.", target: "Calves", time: "4 min" },
  { title: "Leg Circles", desc: "Lie on side, top leg extended. Draw 10 large circles clockwise, then 10 counterclockwise. Switch sides. 3 sets.", target: "Outer thighs", time: "6 min" },
  { title: "Lymphatic Bouncing", desc: "Bounce gently on your toes (or a mini trampoline) for 5 minutes. Activates the lymphatic system which has no pump of its own.", target: "Full body lymph", time: "5 min" },
  { title: "Side-Lying Clams", desc: "Lie on side, knees bent 90°, feet together. Open top knee like a clam shell. 20 reps x 3 sets per side.", target: "Outer hips", time: "5 min" },
  { title: "Reverse Lunges", desc: "Step backward into a lunge, knee hovering above floor. 12 per leg x 3 sets. Control the movement down.", target: "Quads & glutes", time: "6 min" },
];

export const getGutPhase = (day) => {
  if (day <= 7) return GUT_PHASES[0];
  if (day <= 21) return GUT_PHASES[1];
  if (day <= 45) return GUT_PHASES[2];
  return GUT_PHASES[3];
};

export const getGutDayContent = (day) => {
  const idx = day - 1;
  const morningIdx = idx % MORNING_PROTOCOLS.length;
  const eveningIdx = (idx * 7 + 3) % EVENING_PROTOCOLS.length;
  const recipeIdx = (idx * 3 + 5) % GUT_RECIPES.length;
  const tipIdx = (idx * 11 + 2) % DAILY_TIPS.length;
  const exerciseIdx = (idx * 5 + 1) % CELLULITE_EXERCISES.length;

  return {
    phase: getGutPhase(day),
    morningProtocol: MORNING_PROTOCOLS[morningIdx],
    eveningProtocol: EVENING_PROTOCOLS[eveningIdx],
    recipe: GUT_RECIPES[recipeIdx],
    tip: DAILY_TIPS[tipIdx],
    exercise: CELLULITE_EXERCISES[exerciseIdx],
  };
};

export { GUT_PHASES as GUT_PHASE_LIST, GI_SYMPTOMS, GUT_RECIPES, CELLULITE_EXERCISES };
